
default: &default
  adapter: postgresql
  username: ivan
  password: FooBar
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: unicity_dev

test:
  <<: *default
  database: unicity_test

production:
  <<: *default
  database: unicity_dev
